databases:
  - name: servird-db
    plan: free
    databaseName: servird
    user: servird

services:
  - type: web
    name: servird
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: servird-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: POSTGRES_PRISMA_URL
        fromDatabase:
          name: servird-db
          property: connectionString
      - key: POSTGRES_URL_NON_POOLING
        fromDatabase:
          name: servird-db
          property: connectionString
